language: go

go:
  - 1.16
  - tip

before_install:
  - go get -t -v ./...

before_script:
  - make updatepackages

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
